### ISSUE TITLE
Update ALLOWED_HOSTS in settings.py.

### ISSUE THREAD

**Issue by VoroninAA** [TNLinc/TonalCreamAssistant#52]
1. Update allowed hosts in setting ( I guess Subnet mask should be used)
2. Update the container enviromental variables so that `nginx` on `AWS` can succesfully forward traffic.

**Comment by KochankovID** [comment]
Added 3 new env variables: ADMIN_PANEL_ALLOWED_HOSTS, VENDOR_ALLOWED_HOSTS and CV_ALLOWED_HOSTS.

Each of them is a list of strings representing host/domain names that admin panel service can serve. This is a measure to prevent HTTP Host header attacks (you can check .env.example)

Please, check. If everything ok, close issue =)

**Comment by VoroninAA** [comment]
Some issue hapened with a cv service, need to debug before deployment.

**Comment by VoroninAA** [comment]
updated
