### ISSUE TITLE
SSL certificate issue

### ISSUE THREAD

**Issue by KochankovID** [TNLinc/TonalCreamAssistant#69]
So, now we have kind-of three deploy versions:

- local with docker-compose
- staging with Heroku (500 free hours for demonstration)
- prod with AWS (paid)

But, our front hosted on Fleek (another domain). And when we make requests to Heroku or AWS from that domain we have "mixed content" problem, because we don't have SSL on our services.

We have possible solutions:

- [ ] Add SSL on AWS
- [ ] Add front hosting on AWS with the same domain
- [ ] For staging, we can disable browser security for our page
- [ ] We can use Brave with IPFS or Mobile app for demonstration

**Comment by KochankovID** [comment]
https://docs.deta.sh/docs/home/ - probably can move from Heroku to this cloud

**Comment by VoroninAA** [comment]
For demo purposes all origins added to nginx conf. Not needed to configure SSL. Not possible in AWS - needs domain zone.
